-- Inserting Categories for the Store
INSERT INTO Category (category_name) VALUES
    ('Pens, pencils, erasers'),
    ('Notebooks, binders, folders'),
    ('Rulers, protractors, calculators'),
    ('Highlighters, markers, colored pencils'),
    ('Glue sticks, tape, scissors'),
    ('Index cards, Post-it notes'),
    ('School-branded clothing (t-shirts, hoodies, sweatshirts)'),
    ('Uniforms (if applicable)'),
    ('Hats, beanies, caps'),
    ('Socks, gloves, scarves'),
    ('Bottled water, juices, energy drinks'),
    ('Chips, pretzels, popcorn'),
    ('Candy, chocolates, gum'),
    ('Granola bars, trail mix, fruit snacks'),
    ('Pom-poms, foam fingers'),
    ('Megaphones, banners, flags'),
    ('Temporary tattoos, face paint'),
    ('Noise-makers, spirit bells'),
    ('Earphones, headphones'),
    ('USB drives, memory cards'),
    ('Phone chargers, power banks'),
    ('Laptop sleeves, screen protectors'),
    ('Textbooks, study guides'),
    ('Fiction and non-fiction books'),
    ('Magazines, comics'),
    ('Hand sanitizer, tissues'),
    ('Lip balm, moisturizer'),
    ('Hairbrushes, combs'),
    ('Basic first aid supplies'),
    ('Greeting cards, gift wrap'),
    ('Keychains, magnets'),
    ('Stickers, patches'),
    ('Small toys, plushies'),
    ('Yearbooks, class rings'),
    ('Graduation caps and gowns'),
    ('Prom tickets, dance tickets'),
    ('Fundraising items (e.g., cookie dough, coupon books)'),
    ('Laptop cases, sleeves'),
    ('Mouse pads, screen wipes'),
    ('USB hubs, cables'),
    ('Sketchbooks, drawing pencils'),
    ('Paints, brushes, canvases'),
    ('Craft kits, DIY projects'),
    ('Team jerseys, uniforms'),
    ('Water bottles, sports drinks'),
    ('Exercise bands, jump ropes'),
    ('Athletic tape, sweatbands'),
    ('Photos, frames'),
    ('Plaques, trophies'),
    ('School emblems, crests');
